fun main() {
    print("Student Enrollment No:")
    val a=readLine()
    print("Student Name:")
    val b=readLine()
    print("Student Branch:")
    val c=readLine()
    print("Student Class:")
    val d=readLine()
    print("Student Batch:")
    val e=readLine()
    print("Student College Name:")
    val f=readLine()
    print("Student University Name:")
    val g=readLine()
    print("Student Age:")
    val h=readLine()

    println()
    println(a)
    println(b)
    println(c)
    println(d)
    println(e)
    println(f)
    println(g)
    println(h)
}

